development:
  adapter:  postgresql
  encoding: unicode
  database: blocmetrics_development
  pool: 5
  username:
  password:

test:
  adapter:  postgresql
  encoding: unicode
  database: blocmetrics_test
  pool: 5
  username:
  password: